SEPARATE
RUNSUM
RPTSMRY
1 /

SUMTHIN
50 /

-- FIELD RATES / CUMULATIVE
FWCT         Field water cut
FOE          Recovery factor (Field oil recovery):
--           (OIP(initial) - OIP(now)) / OIP(initial)
FGPR
FOPR
FWPR
FLPR

FGPT         Gas Production Total (Cumoil)
FOPT         Oil Production Total (Cumoil)
FWPT         Water Production Total (Cumwat)
FLPT         Liquid Production Total (Cumwat)
FWIT         Water Injection Total (Cumwat)

-- PRESSURE
FPR          Field pressure
FPRH         Field reservoir pressure (hydrocarbon?)
FPRP         Field pressure weighted by pore volume

-- PORE VOLUME
FRPV         Pore Volume at Reservoir
FOPV         Pore Volume containing Oil
FHPV         Pore volume containing hydrocardon
FORMW        Total stock tank oil produced by water influx

-- INIT VOLUME
FGIP         Gas init in place
FGIPG        Gas init in place (gas phase)
FGIPL        Gas init in place (liquid phase)
FOIP         Oil init in place
FOIPG        Oil init in place (gas phase)
FOIPL        Oil init in place (liquid phase)
FWIP         Water initially in place

WBHP
'GAS WELL' 'TOR WELL' 'CER WELL' /

WBHPH
'GAS WELL' 'TOR WELL' 'CER WELL' /

WWIR
'TOR WELL' /

WWIRH
'TOR WELL' /

WGIR
'GAS WELL' /

WGIRH
'GAS WELL' /

WWIT
'TOR WELL' /

WGIT
'GAS WELL' /

WVPR
'CER WELL' /

WVPT
'CER WELL' /

WVIR
'GAS WELL' 'TOR WELL' /

WVIT
'GAS WELL' 'TOR WELL' /

WGOR
'CER WELL' /

WWPR
/

WOPR
/

WGPR
/

WLPR
/

WWPRH
/

WOPRH
/

WGPRH
/

WLPRH
/
-- CURRENT CPU USAGE IN SECONDS
TCPU         
PERFORMA


